#!/bin/bash
#SBATCH --job-name=grpo_1p7b_s15k
#SBATCH --output=log/train/sft_rl/grpo_think_1p7b_sft15000_4gpu.%j.out
#SBATCH --partition=GPUA800,GPUA800S,GPUA800L
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=28
#SBATCH --gres=gpu:4
#SBATCH --mem=400G
#SBATCH --time=240:00:00
set -euo pipefail

# Qwen3-1.7B SFT@15000 → GRPO. Default intended split 2+2.

BASE_DIR=${BASE_DIR:-${SLURM_SUBMIT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}}
export NUM_GPUS=${NUM_GPUS:-4}
export ROLLOUT_GPUS=${ROLLOUT_GPUS:-2}
export TRAIN_GPUS=${TRAIN_GPUS:-2}

MODEL_PATH=${MODEL_PATH:-${BASE_DIR}/outputs/qwen3_1.7b_base/sft_think_4gpu_12k/3299217/checkpoint-15000}
CHAT_TEMPLATE_PATH=${CHAT_TEMPLATE_PATH:-/gpfs/share/home/2501210611/labShare/2501210611/model/qwen3-1.7b}
MODEL_TAG=${MODEL_TAG:-qwen3_1.7b_base}
RUN_NAME=${RUN_NAME:-grpo_think_1p7b_sft15000_4gpu}

TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-64}
PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-32}
PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-2}
LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}
PPO_MAX_TOKEN_LEN_PER_GPU=${PPO_MAX_TOKEN_LEN_PER_GPU:-32768}
MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS:-65536}
VLLM_GPU_MEM_UTIL=${VLLM_GPU_MEM_UTIL:-0.80}

export WANDB_RUN_GROUP=${WANDB_RUN_GROUP:-qwen3_1p7b_sft15000_grpo_dapo}

export BASE_DIR MODEL_PATH CHAT_TEMPLATE_PATH MODEL_TAG RUN_NAME
export TRAIN_BATCH_SIZE PPO_MINI_BATCH_SIZE PPO_MICRO_BATCH_SIZE_PER_GPU
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU PPO_MAX_TOKEN_LEN_PER_GPU MAX_NUM_BATCHED_TOKENS
export VLLM_GPU_MEM_UTIL

exec bash "${BASE_DIR}/scripts/sft_rl/_run_grpo.sh"
